add:
    'anonymous user':
        - 'view any bean_cta bean'
        - 'view any fpo bean'
        - 'view any fpo_hero bean'
        - 'view any sociallinks bean'
        - 'view any twitter bean'
        - 'search content'
    'authenticated user':
        - 'view any bean_cta bean'
        - 'view any fpo bean'
        - 'view any fpo_hero bean'
        - 'view any sociallinks bean'
        - 'view any twitter bean'
        - 'search content'
    admin:
        - 'edit terms in 1'
        - 'delete terms in 1'
        - 'edit terms in 2'
        - 'delete terms in 2'
        - 'administer files'
    editor:
        - 'set tile indexable status'
        - 'create any bean_cta bean'
        - 'delete any bean_cta bean'
        - 'edit any bean_cta bean'
        - 'create any sociallinks bean'
        - 'delete any sociallinks bean'
        - 'edit any sociallinks bean'
        - 'create any twitter bean'
        - 'delete any twitter bean'
        - 'edit any twitter bean'
