add:
    'anonymous user':
        - 'view any bean_container bean'
        - 'view any featuredbean bean'
        - 'view any linkbean bean'
        - 'view any ombubeans_fpo bean'
        - 'view any ombubeans_fpohero bean'
        - 'view any ombubeans_iframe bean'
        - 'view any ombuslide bean'
        - 'search content'
    'authenticated user':
        - 'view any bean_container bean'
        - 'view any featuredbean bean'
        - 'view any linkbean bean'
        - 'view any ombubeans_fpo bean'
        - 'view any ombubeans_fpohero bean'
        - 'view any ombubeans_iframe bean'
        - 'view any ombuslide bean'
        - 'search content'
    admin:
        - 'edit terms in 1'
        - 'delete terms in 1'
        - 'edit terms in 2'
        - 'delete terms in 2'
    editor:
        - 'create any bean_container bean'
        - 'create any featuredbean bean'
        - 'edit any featuredbean bean'
        - 'delete any featuredbean bean'
        - 'create any linkbean bean'
        - 'edit any linkbean bean'
        - 'delete any linkbean bean'
        - 'create any ombubeans_iframe bean'
        - 'create any ombuslide bean'
        - 'delete any bean_container bean'
        - 'delete any ombubeans_iframe bean'
        - 'delete any ombuslide bean'
        - 'edit any bean_container bean'
        - 'edit any ombubeans_iframe bean'
        - 'edit any ombuslide bean'
        - 'set tile indexable status'
