add:
    'anonymous user':
        - 'view any ombubeans_fpo bean'
        - 'view any ombubeans_fpohero bean'
        - 'search content'
    'authenticated user':
        - 'view any ombubeans_fpo bean'
        - 'view any ombubeans_fpohero bean'
        - 'search content'
    admin:
        - 'edit terms in 1'
        - 'delete terms in 1'
        - 'edit terms in 2'
        - 'delete terms in 2'
    editor:
        - 'set tile indexable status'
