add:
    'anonymous user':
        - 'view any fpo bean'
        - 'view any fpo_hero bean'
        - 'search content'
    'authenticated user':
        - 'view any fpo bean'
        - 'view any fpo_hero bean'
        - 'search content'
    admin:
        - 'edit terms in 1'
        - 'delete terms in 1'
        - 'edit terms in 2'
        - 'delete terms in 2'
    editor:
        - 'set tile indexable status'
